"""
Boiler Plate Code Source: https://www.geeksforgeeks.org/working-with-pdf-files-in-python/

Author: Zachary Stewart

Title: PDF Parser

Description:
  Program is intended to in a single command, split a .pdf file generated by an image scanner 
  containing multiple scanned images into multiple .pdf files all containing a single page.

Uses:
  2 possible uses:
    1: user scans all files in a single go
    2: user scans files in grouped batches

TODO:
  Add user friendly method to run program and select file output location
    Currently thinking of converting file into a .exe and introducing it as a folder application stored on desktop
  add method to name files based off parsed contents of file

"""

# importing the required modules
import os
from pypdf import PdfReader, PdfWriter

def PDFsplit(pdf):
  # creating pdf reader object
  reader = PdfReader(pdf)

  # starting index of first slice
  start = 0

  i = start

  # loops through each page of .pdf file
  while i < len(reader.pages):
    # creating pdf writer object for (i+1)th split
    writer = PdfWriter()

    # output pdf file name
    outputpdf = os.getcwd() + "/" + "output_files" + "/" + pdf.split("/")[len(pdf.split("/"))-1].split('.pdf')[0] + " - " + f"{i+1:04}" + '.pdf'

    # Adds single page to .pdf file
    writer.add_page(reader.pages[i])

    # saves .pdf file
    with open(outputpdf, "wb") as f:
      writer.write(f)

    i += 1


# removes old parsed .pdf files to reduce confusion and risk of old files getting reused
def clear_old_files():
  try:
    for filename in os.listdir("./output_files"):
      if filename != ".empty":
        os.remove("./output_files/" + filename)
  except:
    pass



def main():
  # search_location = "./test_files"
  search_location = "./read_files"


  clear_old_files()

  # program runs through all files
  i = 0
  while i < len(os.listdir(search_location)):
    if os.listdir(search_location)[i].endswith('.pdf'):
      PDFsplit(search_location + "/" + os.listdir(search_location)[i])

    i += 1


if __name__ == "__main__":
  # calling the main function
  main()