"""
Boiler Plate Code Source: https://www.geeksforgeeks.org/working-with-pdf-files-in-python/

Author: Zachary Stewart

Title: PDF Parser

Description:
  Program is intended to in a single command, split a .pdf file generated by an image scanner 
  containing multiple scanned images into multiple .pdf files all containing a single page.

Uses:
  2 possible uses:
    1: user scans all files in a single go
    2: user scans files in grouped batches

TODO:
  Add user friendly method to run program and select file output location
    Currently thinking of converting file into a .exe and introducing it as a folder application stored on desktop
  [shouldn't do] Add case for not overwriting files already present
  Change output location to different location
  add method to name files based off parsed contents of file

"""

# importing the required modules
from pypdf import PdfReader, PdfWriter
import os

def PDFsplit(pdf):
  # creating pdf reader object
  reader = PdfReader(pdf)
  # print(len(reader.pages))

  # starting index of first slice
  start = 0

  i = start

  while i < len(reader.pages):
    # creating pdf writer object for (i+1)th split
    writer = PdfWriter()

    # output pdf file name
    # outputpdf = pdf.split('.pdf')[0] + str(i) + '.pdf'
    outputpdf = os.getcwd() + "/" + "output_files" + "/" + pdf.split("/")[len(pdf.split("/"))-1].split('.pdf')[0] + " " + f"{i+1:04}" + '.pdf'

    # no1 = os.getcwd() + "/" + "output_files" + "/" + pdf.split("/")[len(pdf.split("/"))-1].split('.pdf')[0] + str(i) + '.pdf'
    # print(no1)
    # print(os.getcwd())
    # print(os.path.dirname(__file__))



    writer.add_page(reader.pages[i])
    # print(reader.pages[i])
    with open(outputpdf, "wb") as f:
      writer.write(f)

    i += 1


def main():
  # search_location = "./test_files"
  search_location = "./read_files"

  # print(os.listdir(search_location))
  # print(os.listdir(search_location)[0])
  # print(len(os.listdir(search_location)))

  # program runs through all files
  i = 0
  while i < len(os.listdir(search_location)):
    if os.listdir(search_location)[i].endswith('.pdf'):
      PDFsplit(search_location + "/" + os.listdir(search_location)[i])

    i += 1

  # # pdf file to split
  # pdf = './test_files/scan.pdf'

  # # calling PDFsplit function to split pdf
  # PDFsplit(pdf)

if __name__ == "__main__":
  # calling the main function
  main()